# unweighted undirected graph
## adjacency matrix

In [19]:
import numpy as np

In [20]:
0
0.
0 == 0.

0

0.0

True

In [21]:
np.zeros(shape=(10, 3))  # shape= rows, col

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

In [23]:
# using numpy
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in E:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [24]:
# using python

size = len(V)
adjacency_matrix = [[0 for j in range(size)] for i in range(size)]

for (i, j) in E:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 1, 1],
 [0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0]]

## adjacency list

In [25]:
adjacency_list = {}
size = len(V)
for i in range(size):
  adjacency_list[i] = []

for (i, j) in E:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}

# unweighted undirected graph

In [26]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
UE = E + [(j, i) for (i, j) in E]

In [27]:
print(E + [(j, i) for (i, j) in E])

[(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4), (1, 0), (2, 0), (3, 1), (4, 1), (4, 2), (3, 2), (4, 3)]


In [28]:
# using python matrix

size = len(V)
adjacency_matrix = [[0 for j in range(size)] for i in range(size)]

for (i, j) in UE:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [1, 0, 0, 1, 1],
 [1, 0, 0, 1, 1],
 [0, 1, 1, 0, 1],
 [0, 1, 1, 1, 0]]

In [29]:
# using numpy matrix

size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in UE:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [30]:
# list
size = len(V)
adjacency_list = {}

for i in range(size):
  adjacency_list[i] = []

for (i, j) in UE:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4, 0], 2: [4, 3, 0], 3: [4, 1, 2], 4: [1, 2, 3]}

In [31]:
size = len(V)
adjacency_matrix = [[0 for j in range(size)] for i in range(size)]
for (i, j) in UE:
  adjacency_matrix[i][j] = 1

adjacency_matrix

[[0, 1, 1, 0, 0],
 [1, 0, 0, 1, 1],
 [1, 0, 0, 1, 1],
 [0, 1, 1, 0, 1],
 [0, 1, 1, 1, 0]]

In [32]:
size = len(V)
adjacency_list = {}

for i in range(size):
  adjacency_list[i] = []

for (i, j) in UE:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4, 0], 2: [4, 3, 0], 3: [4, 1, 2], 4: [1, 2, 3]}

In [33]:
size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in UE:
  adjacency_matrix[i, j] = 1

adjacency_matrix

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [34]:
size = len(V)
adjacency_list = {}

for i in range(size):
  adjacency_list[i] = []

for (i, j) in UE:
  adjacency_list[i].append(j)

adjacency_list

{0: [1, 2], 1: [3, 4, 0], 2: [4, 3, 0], 3: [4, 1, 2], 4: [1, 2, 3]}

In [35]:
class Queue:
  def __init__(self):
    self.data = []

  def is_empty(self):
    return len(self.data) == 0

  def enqueue(self, value):
    self.data.append(value)

  def dequeue(self):
    if self.is_empty():
      raise Exception('Queue is empty')
    return self.data.pop(0)

  def __str__(self):
    return str(self.data)


queue = Queue()
queue.enqueue(10)
queue.enqueue(11)
print(queue.dequeue())
print(queue.dequeue())
queue.enqueue(12)
print(queue.dequeue())
queue.enqueue(13)


print(queue)

10
11
12
[13]


## Implementation BFS for adjacency list

In [36]:
def bfs_adjacency_list(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True

  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_adjacency_list(adjacency_list, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Implementation BFS for adjacency matrix

In [37]:
import numpy as np

In [38]:
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))

for (i, j) in E:
  adjacency_matrix[i, j] = 1


print(adjacency_matrix)

[[0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [39]:
def get_neighbors(adjacency_matrix, vertex):
  rows, cols = adjacency_matrix.shape
  neighbors = []
  for j in range(cols):
    if adjacency_matrix[vertex, j] == 1:
      neighbors.append(j)

  return neighbors


get_neighbors(adjacency_matrix, 4)

[]

In [40]:
def bfs_adjacency_matrix(adjacency_matrix, start_vertex):
  visited = {}
  rows, cols = adjacency_matrix.shape
  for i in range(rows):
    visited[i] = False
  # print(f'{visited=}')

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = get_neighbors(adjacency_matrix, curr_vertex)
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
  return visited


bfs_adjacency_matrix(adjacency_matrix, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

# Find [traversal order] using BFS

In [41]:
def bfs_traversal_order(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True
  traversal_order = [start_vertex]

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
      traversal_order.append(adj_vertex)

  return (traversal_order, visited)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_traversal_order(adjacency_list, 0)

([0, 1, 2, 3, 4], {0: True, 1: True, 2: True, 3: True, 4: True})

# Find parent of each vertex using BFS

In [42]:
def bfs_parent(adjacency_list, start_vertex):
  visited = {}
  parent = {}
  for vertex in adjacency_list:
    visited[vertex] = False
    parent[vertex] = -1

  queue = Queue()
  queue.enqueue(start_vertex)
  visited[start_vertex] = True

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if visited[adj_vertex]:
        continue
      queue.enqueue(adj_vertex)
      visited[adj_vertex] = True
      parent[adj_vertex] = curr_vertex

  return (visited, parent)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_parent(adjacency_list, 0)

({0: True, 1: True, 2: True, 3: True, 4: True},
 {0: -1, 1: 0, 2: 0, 3: 1, 4: 1})

# Find level number of vertices using BFS

In [43]:
def bfs_level(adjacency_list, start_vertex):
  level = {}
  parent = {}
  for vertex in adjacency_list:
    level[vertex] = -1
    parent[vertex] = -1

  queue = Queue()
  queue.enqueue(start_vertex)
  level[start_vertex] = 0

  while not queue.is_empty():
    curr_vertex = queue.dequeue()
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if level[adj_vertex] == -1:
        queue.enqueue(adj_vertex)
        level[adj_vertex] = level[curr_vertex]+1
        parent[adj_vertex] = curr_vertex
  return (parent, level)


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
bfs_level(adjacency_list, 0)

({0: -1, 1: 0, 2: 0, 3: 1, 4: 1}, {0: 0, 1: 1, 2: 1, 3: 2, 4: 2})

# Depth First Search(DFS)

## Implementation DFS for adjacency list

### using stack

In [44]:
class Stack:
  def __init__(self):
    self.data = []

  def is_empty(self):
    return len(self.data) == 0

  def push(self, value):
    self.data.append(value)

  def pop(self):
    if self.is_empty():
      raise Exception('stack is empty')
    return self.data.pop()

  def __str__(self):
    return str(self.data)


stack = Stack()
stack.push(10)
stack.push(20)
stack.push(30)
print(stack.pop())
print(stack.pop())
stack.push(40)
print(stack.pop())
print(stack)

30
20
40
[10]


In [45]:
def dfs_adjacency_list(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False

  stack = Stack()
  stack.push(start_vertex)

  while not stack.is_empty():
    curr_vertex = stack.pop()
    if visited[curr_vertex]:
      continue
    visited[curr_vertex] = True
    neighbors = adjacency_list[curr_vertex]
    for adj_vertex in neighbors:
      if not visited[adj_vertex]:
        stack.push(adj_vertex)
  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
dfs_adjacency_list(adjacency_list, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

In [46]:
def dfs_adjacency_list(adjacency_list, start_vertex):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False

  stack = Stack()
  stack.push(start_vertex)

  while not stack.is_empty():
    curr_vertex = stack.pop()
    if not visited[curr_vertex]:
      visited[curr_vertex] = True
      neighbors = adjacency_list[curr_vertex]
      for adj_vertex in neighbors:
        if not visited[adj_vertex]:
          stack.push(adj_vertex)
  return visited


adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
dfs_adjacency_list(adjacency_list, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}

### using recursion

In [47]:
def init_dfs_recursive(adjacency_list):
  visited = {}
  for vertex in adjacency_list:
    visited[vertex] = False
  return visited

In [48]:
# Using global variable `visited`

def dfs_adjacency_list_recursive(adjacency_list, curr_vertex):
  visited[curr_vertex] = True  # `visited` is defined outside the function
  neighbors = adjacency_list[curr_vertex]
  for adj_vertex in neighbors:
    if not visited[adj_vertex]:
      visited[adj_vertex] = True
      dfs_adjacency_list_recursive(adjacency_list, adj_vertex)


# test code
adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
visited = init_dfs_recursive(adjacency_list)
dfs_adjacency_list_recursive(adjacency_list, 0)
print(visited)

{0: True, 1: True, 2: True, 3: True, 4: True}


In [49]:
def dfs_adjacency_list_recursive(adjacency_list, curr_vertex, visited):
  visited[curr_vertex] = True

  neighbors = adjacency_list[curr_vertex]
  for adj_vertex in neighbors:
    if not visited[adj_vertex]:
      visited[adj_vertex] = True
      dfs_adjacency_list_recursive(adjacency_list, adj_vertex, visited)
  return visited


# test code
adjacency_list = {0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
visited = init_dfs_recursive(adjacency_list)
dfs_adjacency_list_recursive(adjacency_list, 0, visited)

{0: True, 1: True, 2: True, 3: True, 4: True}

## Implementation DFS for adjacency matrix

### using stack

In [50]:
import numpy as np
V = [0, 1, 2, 3, 4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

size = len(V)
adjacency_matrix = np.zeros(shape=(size, size))
for (i, j) in E:
  adjacency_matrix[i, j] = 1

print(adjacency_matrix)

[[0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [62]:
class Stack:
  def __init__(self):
    self.data = []

  def is_empty(self):
    return len(self.data) == 0

  def push(self, value):
    self.data.append(value)

  def pop(self):
    if self.is_empty():
      raise Exception('stack is empty')
    return self.data.pop()

  def __str__(self):
    return str(self.data)


stack = Stack()
stack.push(12)
stack.push(13)
stack.push(14)
print(stack.pop())
print(stack.pop())
stack.push(15)
print(stack.pop())
print(stack)

14
13
15
[12]


In [55]:
def get_neighbors(adjacency_matrix, vertex):
  rows, cols = adjacency_matrix.shape
  neighbors = []
  for j in range(cols):
    if adjacency_matrix[vertex, j] == 1:
      neighbors.append(j)
  return neighbors


get_neighbors(adjacency_matrix, 3)

[4]

In [67]:
def dfs_adjacency_matrix(adjacency_matrix, start_vertex):
  visited = {}
  rows, cols = adjacency_matrix.shape
  for i in range(rows):
    visited[i] = False

  stack = Stack()
  stack.push(start_vertex)

  while not stack.is_empty():
    curr_vertex = stack.pop()
    if visited[curr_vertex]:
      continue
    visited[curr_vertex] = True

    neighbors = get_neighbors(adjacency_matrix, curr_vertex)
    for adj_vertex in neighbors:
      if not visited[adj_vertex]:
        stack.push(adj_vertex)
  return visited


dfs_adjacency_matrix(adjacency_matrix, 0)

{0: True, 1: True, 2: True, 3: True, 4: True}